# Generated by Django 5.0.2 on 2024-02-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
