# Generated by Django 5.0.2 on 2024-02-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
