# Generated by Django 5.0.2 on 2024-02-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_hidden',
        ),
    ]
