# Generated by Django 5.0.2 on 2024-02-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
    ]
