# Generated by Django 5.0.2 on 2024-02-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinematheater', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinematheater.room')),
            ],
            options={
                'unique_together': {('room', 'row_number', 'row_number')},
            },
        ),
    ]
