# Generated by Django 5.0.2 on 2024-02-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinematheater', '0005_seat_price_movieshow_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
    ]
