# Generated by Django 5.0.2 on 2024-02-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinematheater', '0006_rename_room_name_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=6),
        ),
    ]
