# Generated by Django 5.0.2 on 2024-02-12 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinematheater', '0008_reservation_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Ticket',
        ),
    ]
