# Generated by Django 5.0.2 on 2024-02-12 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinematheater', '0009_rename_reservation_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Reservation',
        ),
    ]
