# Generated by Django 5.0.2 on 2024-02-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinematheater', '0011_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='tickets',
            field=models.ManyToManyField(to='cinematheater.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinematheater.movieshow'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinematheater.seat'),
        ),
    ]
