# Generated by Django 5.0.2 on 2024-02-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinematheater', '0012_remove_reservation_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinematheater.movieshow'),
        ),
    ]
