# Generated by Django 5.0.2 on 2024-02-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinematheater', '0014_reservation_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=1, default=10.0, max_digits=6, null=True),
        ),
    ]
